// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eavrmkwbpsvjhuykzodk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVhdnJta3dicHN2amh1eWt6b2RrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5NTY3MjcsImV4cCI6MjA1OTUzMjcyN30.Y8naHS1lOeIuL_WX_6nmspPi0Jl8iN7zJs_enECg-m4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);